kubernetesClusterDomain: cluster.local
mdAiClientDeployment:
  mdAiClient:
    image:
      repository: tailwindsindia.azurecr.io/majordomo-ai-client
      tag: latest
    imagePullPolicy: Always
  replicas: 1
mdAiClientSvc:
  ports:
  - name: port-1
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: port-2
    port: 8501
    protocol: TCP
    targetPort: 8501
  type: ClusterIP
mdAiCm:
  majordomoAiClientUrl: http://rag-chart-md-ai-client-svc:8000
  majordomoAiControllerUrl: http://rag-chart-md-ai-controller-svc:8000
  mongodbUrl: mongodb://mongodb:27017
  sqlDatabaseUrl: postgres://postgres:postgres@langfuse-postgresql:5432
mdAiControllerDeployment:
  mdAiController:
    image:
      repository: tailwindsindia.azurecr.io/majordomo-ai-controller
      tag: latest
    imagePullPolicy: Always
  replicas: 1
mdAiControllerSvc:
  ports:
  - name: port-1
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: port-2
    port: 8501
    protocol: TCP
    targetPort: 8501
  type: ClusterIP
