apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rag-chart.fullname" . }}-md-ai-controller-deployment
  labels:
  {{- include "rag-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mdAiControllerDeployment.replicas }}
  selector:
    matchLabels:
      app: md-ai-controller
    {{- include "rag-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: md-ai-controller
      {{- include "rag-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - configMapRef:
            name: {{ include "rag-chart.fullname" . }}-md-ai-cm
        image: {{ .Values.mdAiControllerDeployment.mdAiController.image.repository }}:{{
          .Values.mdAiControllerDeployment.mdAiController.image.tag | default .Chart.AppVersion
          }}
        imagePullPolicy: {{ .Values.mdAiControllerDeployment.mdAiController.imagePullPolicy
          }}
        name: md-ai-controller
        ports:
        - containerPort: 8000
        - containerPort: 8501
        resources: {}
      imagePullSecrets:
      - name: acr-secret