apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag-chart.fullname" . }}-md-ai-client-svc
  labels:
  {{- include "rag-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mdAiClientSvc.type }}
  selector:
    app: md-ai-client
  {{- include "rag-chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.mdAiClientSvc.ports | toYaml | nindent 2 }}