apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag-chart.fullname" . }}-md-ai-controller-svc
  labels:
  {{- include "rag-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mdAiControllerSvc.type }}
  selector:
    app: md-ai-controller
  {{- include "rag-chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.mdAiControllerSvc.ports | toYaml | nindent 2 }}