apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rag-chart.fullname" . }}-llm-ingress-controller
  labels:
  {{- include "rag-chart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/controller)$ $1/ redirect;
    nginx.ingress.kubernetes.io/proxy-max-temp-file-size: 1024m
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: '{{ include "rag-chart.fullname" . }}-md-ai-controller-svc'
            port:
              number: 8501
        path: /controller(/|$)(.*)
        pathType: Prefix