apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rag-chart.fullname" . }}-llm-ingress-monitoring
  labels:
  {{- include "rag-chart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      location ~* \.js$ {
        add_header Content-Type application/javascript;
      }
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: langfuse
            port:
              number: 3000
        path: /monitoring
        pathType: Prefix