{{ if .Values.blue.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "blue-green.fullname" . }}-blue
  labels:
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "blue-green.name" . }}
    version: {{ .Values.blue.appVersion | quote }}
    tailwinds.ai/support-blue-green: "true"
    tailwinds.ai/blue-green-type: blue
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "blue-green.name" . }}
      version: {{ .Values.blue.appVersion | quote }}
      release: {{ .Release.Name }}
      slot: blue
  template:
    metadata:
      annotations:
        enable.version-checker.io/{{ template "blue-green.name" . }}-blue: "true"
      labels:
        app: {{ template "blue-green.name" . }}
        version: {{ .Values.blue.appVersion | quote }}
        release: {{ .Release.Name }}
        slot: blue
    spec:
      containers:
        - name: {{ template "blue-green.name" . }}-blue
          image: nginx:{{ .Values.blue.image_tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # This (and the volumes section below) mount the config map as a volume.
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: wwwdata-volume
      volumes:
        - name: wwwdata-volume
          emptyDir: {}
{{ end }}
