apiVersion: v1
kind: Service
metadata:
  service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Application=back-end,ITLT_Owner=al.mujtaba@iff.com"
  name: "{{ .Values.name }}"
  labels:
    app: "{{ .Values.name }}"
spec:
  type: LoadBalancer
  selector:
    app: "{{ .Values.name }}"
  ports:
    - port: 3080
      targetPort: 49160
